#!/usr/bin/env bash
echo "Open 3 terminals and run:"
echo ""
echo "1) Risk service:"
echo "   cd risk-service"
echo "   python3 -m venv .venv"
echo "   source .venv/bin/activate"
echo "   pip install -r requirements.txt"
echo "   uvicorn app.main:app --reload --port 8000"
echo ""
echo "2) Core API:"
echo "   cd core-api"
echo "   ./gradlew bootRun"
echo ""
echo "3) Dashboard (later, when you install deps):"
echo "   cd dashboard"
echo "   npm install"
echo "   npm run dev"
